# Generated by Django 5.2.3 on 2025-07-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-applied_date']},
        ),
    ]
