# Generated by Django 5.2.3 on 2025-08-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['key']},
        ),
    ]
