# Generated by Django 5.2.3 on 2025-08-31 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_timesta_80074f_idx',
            old_name='core_audit_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_d9fb24_idx',
            old_name='core_audit_action_idx',
        ),
    ]
