# Generated by Django 5.2.3 on 2025-07-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_customuser_role_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
