# Generated by Django 5.2.3 on 2025-08-31 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_complaint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='complaint',
            new_name='hr_complain_type_e19e75_idx',
            old_name='hr_complain_type_sta_0b1f6a_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='hr_complain_created_907691_idx',
            old_name='hr_complain_created__bf7681_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='hr_complain_target__6ca353_idx',
            old_name='hr_complain_target__0bb167_idx',
        ),
    ]
