# Generated by Django 5.2.3 on 2025-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_department_code_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(default='DEFAULT_CODE', max_length=50, unique=True),
        ),
    ]
