# Generated by Django 5.2.3 on 2025-08-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_attendance_employee_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
