# Generated by GitHub Copilot on 2025-08-13
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hr', '0007_attendance_deleted_at_customuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='work_duration',
            field=models.DurationField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('hr', 'HR'), ('ceo', 'CEO')], default='employee', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='uniq_attendance_employee_date'),
        ),
    ]
