# Generated by Django 5.2.3 on 2025-08-14 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_department_deleted_at'),
        ('hr', '0008_attendance_work_duration_role_choice_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_value', models.IntegerField(default=1)),
                ('max_value', models.IntegerField(default=5)),
                ('labels', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_type',
            field=models.CharField(choices=[('annual', 'Annual'), ('mid', 'Mid-year'), ('probation', 'Probation')], default='annual', max_length=32),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='self_assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_review', 'Manager Review'), ('calibration', 'Calibration'), ('finalized', 'Finalized'), ('archived', 'Archived')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('at_risk', 'At Risk'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('visibility', models.CharField(default='team', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='department.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalKeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('metric_type', models.CharField(choices=[('numeric', 'Numeric'), ('percent', 'Percent'), ('binary', 'Binary')], default='numeric', max_length=32)),
                ('baseline', models.FloatField(blank=True, null=True)),
                ('target', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='hr.goal')),
            ],
        ),
        migrations.CreateModel(
            name='GoalParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('contributor', 'Contributor'), ('watcher', 'Watcher')], default='contributor', max_length=32)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='hr.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='hr.goal')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='hr.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('rating_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competencies', to='hr.ratingscale')),
            ],
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='hr.reviewcycle'),
        ),
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together={('employee', 'review_cycle', 'review_type')},
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['employee'], name='hr_performa_employe_d6c364_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['review_cycle'], name='hr_performa_review__936262_idx'),
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.competency'),
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='hr.performancereview'),
        ),
        migrations.AddField(
            model_name='reviewsnapshot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewsnapshot',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='hr.performancereview'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AlterUniqueTogether(
            name='goalparticipant',
            unique_together={('goal', 'user')},
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='score',
        ),
        migrations.AlterUniqueTogether(
            name='reviewscore',
            unique_together={('review', 'competency')},
        ),
    ]
