# Generated by Django 5.2.3 on 2025-08-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_ratingscale_reviewcycle_reviewscore_reviewsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email']},
        ),
    ]
