# Generated by Django 5.2.3 on 2025-07-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_attendance_department_leaverequest_performancereview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='performancereview',
            table='hr_performancereview',
        ),
    ]
