# Generated by Django 5.2.3 on 2025-08-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_department_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
    ]
